INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (1,'1','P_BUC_01','Old Age Pension Claim');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (2,'1','P_BUC_02','Survivors Pension Claim');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (3,'1','P_BUC_03','Invalidity Pension Claim');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (4,'1','P_BUC_04','Request for Information about Child Raising Periods');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (5,'1','P_BUC_05','Adhoc Request for Pension Information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (6,'1','P_BUC_06','Notification of Pension Information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (7,'1','P_BUC_07','Request for Pension Amounts to Determine Supplements');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (8,'1','P_BUC_08','Information on pension amount to award a pension supplement');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (9,'1','P_BUC_09','Change in personal circumstances');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (10,'1','P_BUC_10','Transitional cases');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (11,'4','H_BUC_01','Adhoc Exchange of Information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (12,'4','H_BUC_02a','Determine Residence - Request for information on residence');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (13,'4','H_BUC_02b','Determine Residence - Disagreement with decision');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (14,'4','H_BUC_02c','Determine Residence - Notification on state of residence');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (15,'4','H_BUC_03a','Change of Legislation Applicable - Notification');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (16,'4','H_BUC_03b','Change of Legislation Applicable - Request for information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (17,'4','H_BUC_04','Reimbursement of Administrative Check or Medical examination');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (18,'4','H_BUC_05','Exchange of PINs');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (19,'4','H_BUC_06','Transfer of Claim');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (20,'4','H_BUC_07','Notification of Death');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (21,'4','H_BUC_08','Request for Medical Report');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (22,'4','H_BUC_09','Notification of Medical Information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (23,'4','H_BUC_10','Request for Administrative Check');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (24,'6','R_BUC_01','Offsetting of OverPayment of Benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (25,'6','R_BUC_02','Offsetting of OverPayment with Arrears');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (26,'6','R_BUC_03','Offsetting of provisionally paid benefits with Payments of another Member State under Art. 73 (1) of Regulation 987/2009');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (27,'6','R_BUC_04','Offsetting of provisionally received contributions with contributions payable in another Member State...');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (28,'6','R_BUC_05','Request for information under Article 76 of Regulation (EC) No 987/2009');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (29,'6','R_BUC_06','Request for notification under Article 77 of Regulation (EC) No. 987/2009');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (30,'6','R_BUC_07','Request for recovery');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (31,'3','FB_BUC_01','Determine Competences');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (32,'3','FB_BUC_02','Discharges of Family Benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (33,'3','FB_BUC_03','Additional family benefits for orphans');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (34,'3','FB_BUC_04','Information about payment regarding priority right');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (35,'8','S_BUC_01','Entitlement - Residence outside Competent Member State - Without PD');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (36,'8','S_BUC_01a','Entitlement - Residence outside Competent Member State without PD - Entitlement document issued by Competent State');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (37,'8','S_BUC_02','Entitlement - Residence outside Competent Member State - With PD');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (38,'8','S_BUC_03','Cancellation of entitlement document');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (39,'8','S_BUC_04','Cancellation of registration');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (40,'8','S_BUC_05','Necessary Treatment in Member State of Stay - Request for Entitlement Document');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (41,'8','S_BUC_06','Necessary or Scheduled Treatment - Reimbursement Rates');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (42,'8','S_BUC_07','Scheduled Treatment - Information on Coverage of Specific Benefit in Kind');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (43,'8','S_BUC_08','Scheduled treatment - Request Entitlement Document in Member State of Stay (Residence not in competent Member State)');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (44,'8','S_BUC_09','Scheduled treatment - Request extension of authorisation in Member State of Stay');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (45,'8','S_BUC_11','Urgent vitally necessary treatment - Request for authorisation in Member State of residence');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (46,'8','S_BUC_12','Application for Cash Benefits Related to Incapacity for Work');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (47,'8','S_BUC_14','Information on Payment or not of Cash Benefits in respect of Incapacity for Work');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (48,'8','S_BUC_14a','Information Related to Cash Benefits in Respect of Incapacity for Work - given by Competent Institution');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (49,'8','S_BUC_14b','Information Related to Cash Benefits in Respect of Incapacity for Work - given by institution of place of residence or stay');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (50,'8','S_BUC_15','Long Term Care Cash Benefits - Application');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (51,'8','S_BUC_17','Long-Term Care Cash Benefits - Information on Payment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (52,'8','S_BUC_17a','Long-Term Care Cash Benefits - Change or Cancellation');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (53,'8','S_BUC_18','Request for entitlement document for Former Frontier Workers');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (54,'8','S_BUC_18a','Change or cancellation of entitlement document of a former frontier worker / family member of a former frontier worker');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (55,'8','S_BUC_19','Actual Cost Claim - Benefits in Kind');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (56,'8','S_BUC_21','Inventory of months - Fixed amounts');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (57,'8','S_BUC_22','Claim for Interest on late Payment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (58,'8','S_BUC_23','Refund of Overpayment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (59,'8','S_BUC_24','Aggregation of Periods - Insurance Risk Type : Sickness, Paternity and Maternity');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (60,'7','UB_BUC_01','Exchange of Information to Determine a Claim for UB');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (61,'7','UB_BUC_02','Export of unemployment benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (62,'7','UB_BUC_03','Simultaneous registration');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (63,'7','UB_BUC_04','Reimbursement of unemployment benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (64,'2','AW_BUC_01a','Certification right benefit in Kind - Member State of stay/residence request confirmation of rights');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (65,'2','AW_BUC_01b','Certification right benefit in Kind - Competent Member State sends the Certification');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (66,'2','AW_BUC_02','Cancellation Certification right benefit in Kind');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (67,'2','AW_BUC_03','Establishing the reimbursement rates');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (68,'2','AW_BUC_04a','Authorisation to receive scheduled treatment in a Member State other than...');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (69,'2','AW_BUC_04b','Information about supplement scheduled treatment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (70,'2','AW_BUC_04c','Information about granting of authorisation to receive scheduled urgent vitally necessary treatment...');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (71,'2','AW_BUC_05','Claim for Reimbursement of Benefit in Kind');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (72,'2','AW_BUC_06a','Application for cash benefits in respect of accident at work and occupational disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (73,'2','AW_BUC_06b','Information on payment or not of cash benefits in respect of accident at work and occupational disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (74,'2','AW_BUC_06c','Information on end of incapacity for work in respect of accident at work and occupational disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (75,'2','AW_BUC_07a','Notification of medical certificate for AWOD benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (76,'2','AW_BUC_07b','Appointment of a person for the purpose of performing an inquiry - accident while travelling to or from work');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (77,'2','AW_BUC_07c','Benefits in kind - Detailed report');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (78,'2','AW_BUC_07d','Decision setting the date for the recovery or stabilization of injuries / concerning granting of a pension');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (79,'2','AW_BUC_08','Contestation of the application of the legislation related to accidents at work or occupational diseases');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (80,'2','AW_BUC_09a','Forwarding of Declaration or Notification of Occupational Disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (81,'2','AW_BUC_09b','Notification that Conditions are not Fulfilled and Forwarding of Declaration or Notification of Occupational Disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (82,'2','AW_BUC_10a','Exchange of information between institutions and advance payments in the event of an appeal against rejection');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (83,'2','AW_BUC_10b','Information about an advance payments');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (84,'2','AW_BUC_11','Aggravation of an occupational disease');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (85,'2','AW_BUC_12','Information about the degree of incapacity for work');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (86,'2','AW_BUC_13','Forward a claim for pensions or supplementary allowances to Competent Member State');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (87,'2','AW_BUC_14','Cost of Transport');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (88,'2','AW_BUC_15','Claim interest for late payment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (89,'2','AW_BUC_23','Identification of the Overpayment');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (90,'9','LA_BUC_01','Request for Exceptions');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (91,'9','LA_BUC_02','Determination of Legislation Applicable');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (92,'9','LA_BUC_03','Notification of Relevant Information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (93,'9','LA_BUC_04','Notification of Posting');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (94,'9','LA_BUC_05','Notification of applicable legislation');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (95,'9','LA_BUC_06','Request for more information');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (96,'5','M_BUC_01','Claim for Death Grant');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (97,'5','M_BUC_02','Claim for pre-retirement Benefit');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (98,'5','M_BUC_03a','Exchange of information concerning the amount of income for special non-contributory cash benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (99,'5','M_BUC_03b','Exchange of information concerning periods of employment/self-employment/ residence for special non-contributory cash benefits');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (100,'10','SYNC_SUC_02','IR Synchronization upon Request');
INSERT INTO process_def(sid, fk_sector_sid,id, name) VALUES (101,'10','SYNC_SUC_04','CDM Synchronization upon Request');
ALTER SEQUENCE process_def_seq RESTART WITH 102;
