ALTER SEQUENCE rina.supported_language_seq RESTART WITH 25;

INSERT INTO rina.supported_language (sid, lang) VALUES (01, 'bg');
INSERT INTO rina.supported_language (sid, lang) VALUES (02, 'cs');
INSERT INTO rina.supported_language (sid, lang) VALUES (03, 'da');
INSERT INTO rina.supported_language (sid, lang) VALUES (04, 'de');
INSERT INTO rina.supported_language (sid, lang) VALUES (05, 'en');
INSERT INTO rina.supported_language (sid, lang) VALUES (06, 'el');
INSERT INTO rina.supported_language (sid, lang) VALUES (07, 'es');
INSERT INTO rina.supported_language (sid, lang) VALUES (08, 'et');
INSERT INTO rina.supported_language (sid, lang) VALUES (09, 'fi');
INSERT INTO rina.supported_language (sid, lang) VALUES (10, 'fr');
INSERT INTO rina.supported_language (sid, lang) VALUES (11, 'hr');
INSERT INTO rina.supported_language (sid, lang) VALUES (12, 'hu');
INSERT INTO rina.supported_language (sid, lang) VALUES (13, 'it');
INSERT INTO rina.supported_language (sid, lang) VALUES (14, 'lt');
INSERT INTO rina.supported_language (sid, lang) VALUES (15, 'lv');
INSERT INTO rina.supported_language (sid, lang) VALUES (16, 'mt');
INSERT INTO rina.supported_language (sid, lang) VALUES (17, 'nl');
INSERT INTO rina.supported_language (sid, lang) VALUES (18, 'no');
INSERT INTO rina.supported_language (sid, lang) VALUES (19, 'pl');
INSERT INTO rina.supported_language (sid, lang) VALUES (20, 'pt');
INSERT INTO rina.supported_language (sid, lang) VALUES (21, 'ro');
INSERT INTO rina.supported_language (sid, lang) VALUES (22, 'sk');
INSERT INTO rina.supported_language (sid, lang) VALUES (23, 'sl');
INSERT INTO rina.supported_language (sid, lang) VALUES (24, 'sv');
