delete from action_tag where fk_action_sid in (select sid from "action" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from "action" where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from assignment_group where fk_assignment_sid in (select sid from "assignment" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from assignment_user where fk_assignment_sid in (select sid from "assignment" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from "assignment" where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_participant where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_prefill where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_comment where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_property where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_attachment where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from case_subject_org where fk_case_sid in (select sid from rina_case where id=:caseId);
update subdocument_bversion set fk_subdoc_content_sid=null where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from subdocument_content where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
update "subdocument" set fk_subdoc_bversion_sid=null where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from subdoc_bversion_attachment where fk_subdoc_bversion_sid in (SELECT sid from subdocument_bversion where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId)));
delete from subdocument_bversion where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from subdocument_attachment where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from subdocument_prefill where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from subdocument_history where fk_subdoc_sid in (select sid from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from "subdocument" where fk_case_sid in (select sid from rina_case where id=:caseId);
update document_bversion set fk_doc_content_sid=null where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from document_content where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
update "document" set fk_doc_bversion_sid=null where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from conv_participant where fk_conv_sid in (select sid from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId)));
delete from signature where fk_message_sid in (select sid from user_message where fk_doc_conv_sid in (select sid from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId))));
delete from user_message_response where fk_message_sid in (select sid from user_message where fk_doc_conv_sid in (select sid from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId))));
delete from user_message where fk_doc_conv_sid in (select sid from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId)));
delete from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from doc_bversion_attachment where fk_doc_bversion_sid in (SELECT sid from document_bversion where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId)));
delete from document_history where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from document_bversion where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from document_attachment where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from document_conversation where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from document_comment where fk_doc_sid in (select sid from "document" where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from "document" where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from notification_user where fk_notification_sid in (select sid from notification where fk_case_sid in (select sid from rina_case where id=:caseId));
delete from notification where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from notification_alarm where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from temp_document where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from temp_action where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from temp_attachment where fk_case_sid in (select sid from rina_case where id=:caseId);
delete from rina_case where id=:caseId;